const KEY='maitreeInstituteV1';
const defaults={students:[],inquiries:[],courses:[{id:'c1',name:'MS-CIT',fees:4500,duration:'3 Months'},{id:'c2',name:'Tally Prime',fees:5000,duration:'3 Months'},{id:'c3',name:'Advanced Excel',fees:3500,duration:'2 Months'}]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||defaults; save(); let chart1,chart2;
function save(){localStorage.setItem(KEY,JSON.stringify(db))} function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')} function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
const pages={dashboard:['Dashboard','Institute overview and monthly registrations'],students:['Students','Manage registrations and export records'],registration:['New Registration','Add a student and payment details'],inquiries:['Inquiries','Track prospective students and follow-ups'],courses:['Courses','Manage your institute courses'],fees:['Fees','Payment collection and pending fees']};
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.getElementById('pageTitle').textContent=pages[p][0];document.getElementById('pageSub').textContent=pages[p][1];if(p==='dashboard')renderDashboard();if(p==='students')renderStudents();if(p==='inquiries')renderInquiries();if(p==='courses')renderCourses();if(p==='fees')renderFees();window.scrollTo(0,0)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));document.addEventListener('click',e=>{let g=e.target.closest('[data-go]');if(g)go(g.dataset.go)});document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.getElementById('today').textContent=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
function nextId(){let y=new Date().getFullYear();return `MCI-${y}-${String(db.students.length+1).padStart(4,'0')}`}
function fillCourses(){sCourse.innerHTML='<option value="">Select course</option>'+db.courses.map(c=>`<option value="${esc(c.name)}" data-fees="${c.fees}">${esc(c.name)}</option>`).join('');}
sCourse.onchange=()=>{let o=sCourse.selectedOptions[0];if(o&&o.dataset.fees)sFees.value=o.dataset.fees};sDate.value=new Date().toISOString().slice(0,10);fillCourses();
studentForm.onsubmit=e=>{e.preventDefault();let fees=+sFees.value||0,discount=+sDiscount.value||0,final=Math.max(0,fees-discount),paid=+sPaid.value||0;if(paid>final)return toast('Initial payment cannot exceed final fees');let obj={id:editId.value||nextId(),name:sName.value.trim(),mobile:sMobile.value.trim(),address:sAddress.value.trim(),course:sCourse.value,fees,discount,finalFees:final,paid,payments:paid?[{date:sDate.value,amount:paid,mode:sMode.value}]:[],date:sDate.value,notes:sNotes.value.trim()};if(editId.value){let i=db.students.findIndex(x=>x.id===editId.value);db.students[i]=obj;toast('Student updated')}else{db.students.push(obj);toast('Student registered: '+obj.id)}save();studentForm.reset();editId.value='';sDate.value=new Date().toISOString().slice(0,10);sDiscount.value=0;sPaid.value=0;document.getElementById('saveStudent').textContent='Add Student';fillCourses();go('students');};
function renderDashboard(){let now=new Date(),labels=[],vals=[];for(let i=11;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1);labels.push(d.toLocaleDateString('en-IN',{month:'short'}));vals.push(db.students.filter(s=>{let x=new Date(s.date);return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()}).length)}statStudents.textContent=db.students.length;statMonth.textContent=vals[11]||0;statInquiries.textContent=db.inquiries.length;statPending.textContent=money(db.students.reduce((a,s)=>a+(s.finalFees-(s.paid||0)),0));let ctx=document.getElementById('registrationChart');if(chart1)chart1.destroy();chart1=new Chart(ctx,{type:'bar',data:{labels,datasets:[{label:'Students',data:vals,borderWidth:1,borderRadius:5}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});let cm=db.courses.map(c=>c.name),cv=cm.map(c=>db.students.filter(s=>s.course===c).length);let ctx2=document.getElementById('courseChart');if(chart2)chart2.destroy();chart2=new Chart(ctx2,{type:'doughnut',data:{labels:cm.length?cm:['No students'],datasets:[{data:cm.length?cv:[1]}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}});let recent=[...db.students].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);recentStudents.innerHTML=recent.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Course</th><th>Fees</th><th>Pending</th></tr></thead><tbody>${recent.map(s=>`<tr><td>${esc(s.id)}</td><td><strong>${esc(s.name)}</strong></td><td>${esc(s.course)}</td><td>${money(s.finalFees)}</td><td>${money(s.finalFees-s.paid)}</td></tr>`).join('')}</tbody></table></div>`:'<p style="color:#777">No registrations yet.</p>'}
function renderStudents(){let q=(studentSearch.value||'').toLowerCase();let a=db.students.filter(s=>(s.name+' '+s.mobile+' '+s.course+' '+s.id).toLowerCase().includes(q));studentTable.innerHTML=a.length?a.map(s=>`<tr><td>${esc(s.id)}</td><td><strong>${esc(s.name)}</strong></td><td>${esc(s.mobile)}</td><td>${esc(s.course)}</td><td>${money(s.finalFees)}</td><td>${money(s.paid)}</td><td>${money(s.finalFees-s.paid)}</td><td>${esc(s.date)}</td><td><button class="action-btn" onclick="viewStudent('${s.id}')">View</button><button class="action-btn" onclick="editStudent('${s.id}')">Edit</button><button class="action-btn danger" onclick="deleteStudent('${s.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="9">No students found.</td></tr>'}
studentSearch.oninput=renderStudents;
function editStudent(id){let s=db.students.find(x=>x.id===id);if(!s)return;go('registration');editId.value=s.id;sName.value=s.name;sMobile.value=s.mobile;sAddress.value=s.address;sDate.value=s.date;sFees.value=s.fees;sDiscount.value=s.discount;sPaid.value=s.paid;sNotes.value=s.notes;fillCourses();sCourse.value=s.course;saveStudent.textContent='Update Student';}
function deleteStudent(id){if(!confirm('Delete this student?'))return;db.students=db.students.filter(s=>s.id!==id);save();renderStudents();toast('Student deleted')}
function viewStudent(id){let s=db.students.find(x=>x.id===id);modalContent.innerHTML=`<h2>${esc(s.name)}</h2><p><b>Student ID:</b> ${esc(s.id)}<br><b>Mobile:</b> ${esc(s.mobile)}<br><b>Address:</b> ${esc(s.address||'-')}<br><b>Course:</b> ${esc(s.course)}<br><b>Registration:</b> ${esc(s.date)}</p><hr><p><b>Final Fees:</b> ${money(s.finalFees)} &nbsp; <b>Paid:</b> ${money(s.paid)} &nbsp; <b>Pending:</b> ${money(s.finalFees-s.paid)}</p><h3>Installment History</h3>${s.payments?.length?`<table><thead><tr><th>Date</th><th>Amount</th><th>Mode</th></tr></thead><tbody>${s.payments.map(p=>`<tr><td>${esc(p.date)}</td><td>${money(p.amount)}</td><td>${esc(p.mode)}</td></tr>`).join('')}</tbody></table>`:'<p>No payments recorded.</p>'}<div class="form-actions"><button class="btn wa" onclick="whatsapp('${s.mobile}','Hello ${esc(s.name)}, this is Maitree Computer Institute. Your pending fee is ${money(s.finalFees-s.paid)}. Please contact us for details.')">WhatsApp</button><button class="btn primary" onclick="window.print()">Print</button></div>`;modal.classList.remove('hidden')}
function whatsapp(num,msg){let clean=String(num).replace(/\D/g,'');if(clean.length===10)clean='91'+clean;window.open('https://wa.me/'+clean+'?text='+encodeURIComponent(msg),'_blank')}
function renderInquiries(){inquiryTable.innerHTML=db.inquiries.length?db.inquiries.map(i=>`<tr><td><strong>${esc(i.name)}</strong></td><td>${esc(i.mobile)}</td><td>${esc(i.course||'-')}</td><td>${esc(i.follow||'-')}</td><td><span class="status ${esc(i.status).replaceAll(' ','-')}">${esc(i.status)}</span></td><td><button class="action-btn wa" onclick="whatsapp('${i.mobile}','Hello ${esc(i.name)}, this is Maitree Computer Institute. Thank you for your inquiry. How can we help you?')">WhatsApp</button><button class="action-btn danger" onclick="deleteInquiry('${i.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="6">No inquiries yet.</td></tr>'}
newInquiryBtn.onclick=()=>inquiryFormWrap.classList.remove('hidden');cancelInquiry.onclick=()=>inquiryFormWrap.classList.add('hidden');inquiryForm.onsubmit=e=>{e.preventDefault();db.inquiries.push({id:crypto.randomUUID(),name:iName.value.trim(),mobile:iMobile.value.trim(),address:iAddress.value.trim(),course:iCourse.value.trim(),follow:iFollow.value,status:iStatus.value,notes:iNotes.value.trim(),date:new Date().toISOString().slice(0,10)});save();inquiryForm.reset();inquiryFormWrap.classList.add('hidden');renderInquiries();toast('Inquiry saved')};function deleteInquiry(id){if(confirm('Delete this inquiry?')){db.inquiries=db.inquiries.filter(i=>i.id!==id);save();renderInquiries()}}
function renderCourses(){courseTable.innerHTML=db.courses.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${money(c.fees)}</td><td>${esc(c.duration)}</td><td><button class="action-btn danger" onclick="deleteCourse('${c.id}')">Delete</button></td></tr>`).join('')}
addCourseBtn.onclick=()=>{let name=prompt('Course name');if(!name)return;let fees=+prompt('Standard fees (₹)','0');let duration=prompt('Duration','3 Months')||'';db.courses.push({id:crypto.randomUUID(),name,fees:fees||0,duration});save();fillCourses();renderCourses();toast('Course added')};function deleteCourse(id){if(confirm('Delete course?')){db.courses=db.courses.filter(c=>c.id!==id);save();fillCourses();renderCourses()}}
function renderFees(){let total=db.students.reduce((a,s)=>a+s.finalFees,0),paid=db.students.reduce((a,s)=>a+s.paid,0);feeTotal.textContent=money(total);feeCollected.textContent=money(paid);feeDue.textContent=money(total-paid);feeTable.innerHTML=db.students.filter(s=>s.finalFees>s.paid).map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.course)}</td><td>${money(s.finalFees)}</td><td>${money(s.paid)}</td><td>${money(s.finalFees-s.paid)}</td><td><button class="action-btn wa" onclick="whatsapp('${s.mobile}','Hello ${esc(s.name)}, this is Maitree Computer Institute. Your pending fee is ${money(s.finalFees-s.paid)}. Kindly pay your pending amount. Thank you.')">WhatsApp</button></td></tr>`).join('')||'<tr><td colspan="6">No pending fees 🎉</td></tr>'}
exportStudents.onclick=()=>{let rows=db.students.map(s=>({Student_ID:s.id,Name:s.name,Mobile:s.mobile,Address:s.address,Course:s.course,Final_Fees:s.finalFees,Paid:s.paid,Pending:s.finalFees-s.paid,Registration_Date:s.date}));let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Students');XLSX.writeFile(wb,'Maitree_Students.xlsx')};
backupBtn.onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='Maitree_Backup.json';a.click();URL.revokeObjectURL(a.href)};restoreBtn.onclick=()=>restoreFile.click();restoreFile.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();location.reload()}catch{alert('Invalid backup file')}};r.readAsText(f)};
closeModal.onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
renderDashboard();
